use std::path::{Component, Path};

use crate::core::git::types::FileCategory;

/// Exact basename match
/// Precision > recall
const LOCK_FILES: &[&str] = &[
    // JS / TS
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lock",
    "deno.lock",
    // Rust
    "Cargo.lock",
    // Go
    "go.sum",
    "go.work.sum",
    "Gopkg.lock",
    "glide.lock",
    // Python
    "Pipfile.lock",
    "poetry.lock",
    "pdm.lock",
    "uv.lock",
    "conda-lock.yml",
    "conda-lock.yaml",
    "pixi.lock",
    // Ruby
    "Gemfile.lock",
    "gems.locked",
    // PHP
    "composer.lock",
    // Dart / Flutter
    "pubspec.lock",
    // Elixir / Erlang
    "mix.lock",
    "rebar.lock",
    // .NET
    "packages.lock.json",
    "paket.lock",
    // Apple / Swift
    "Package.resolved",
    "Podfile.lock",
    "Cartfile.resolved",
    // C / C++
    "conan.lock",
    "vcpkg-lock.json",
    // JVM
    "gradle.lockfile",
    "MODULE.bazel.lock",
    // Infra
    ".terraform.lock.hcl",
    "flake.lock",
    "Chart.lock",
    "helmfile.lock",
    // Misc package managers (high-signal names only)
    "shard.lock",
    "stack.yaml.lock",
    "cabal.project.freeze",
    "cpanfile.snapshot",
    "dub.selections.json",
    "renv.lock",
    "jsonnetfile.lock.json",
    "Brewfile.lock.json",
    "Berksfile.lock",
    "Policyfile.lock.json",
    "Puppetfile.lock",
    "spack.lock",
];

/// Directory component names that strongly indicate generated code
const GENERATED_DIR_NAMES: &[&str] = &[
    "generated",
    "generated-sources",
    "generated_sources",
    "generated-test-sources",
    "__generated__",
    "_generated",
    "gen",
    "gensrc",
];

/// Basename suffixes
const GENERATED_NAME_SUFFIXES: &[&str] = &[
    // protobuf / gRPC — all mainstream languages
    ".pb.cc",
    ".pb.h",
    ".pb.go",
    ".pb.rs",
    ".pb.swift",
    ".pb.ts",
    ".pb.js",
    ".pb.dart",
    ".pbgrpc.dart",
    "_pb.py",
    "_pb.js", // protoc JS actually emits `foo_pb.js`
    "_pb2.py",
    "_pb_grpc.py",
    "_pb2_grpc.py",
    // .NET source generators & VS designers
    ".g.cs",
    ".designer.cs",
    // Dart build_runner
    ".g.dart",
    ".freezed.dart",
    ".mocks.dart",
    // explicit codegen infixes (buf / oapi-codegen conventions)
    ".gen.go",
    ".gen.ts",
    ".gen.rs",
    ".codegen.js",
    ".codegen.ts",
    // explicit generated infixes
    ".generated.go",
    ".generated.js",
    ".generated.jsx",
    ".generated.ts",
    ".generated.tsx",
    "_generated.go",
    "_generated.h",
    "_generated.java",
    "_generated.js",
    "_generated.py",
    "_generated.rs",
    "_generated.ts",
    // bundler output & sourcemaps
    ".min.css",
    ".min.js",
    ".min.mjs",
    ".js.map",
    ".mjs.map",
    ".css.map",
    ".snap",
    ".pbxproj",
];

const GENERATED_HEADER_MARKERS: &[&str] = &[
    "@generated",
    "code generated by",
    "auto-generated",
    "autogenerated",
    "generated by the protocol buffer compiler",
    "generated by protoc",
];

const GENERATED_LINE_PHRASES: &[&str] = &[
    "this file was generated",
    "this file is generated",
    "automatically generated",
];

const EDIT_WARNING_MARKERS: &[&str] = &["do not edit", "do not modify"];

const GENERATION_STEM: &str = "generat";
const GENERATOR_LEAD: &str = "generated by";
const COMMENT_PREFIXES: &[&str] = &["<!--", "//", "/*", "*", "#", "--", ";"];

/// Basename against lockfile registry
pub fn match_lock_file(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };

    LOCK_FILES
        .iter()
        .any(|lock| name.eq_ignore_ascii_case(lock))
}

pub fn match_generated_path(path: &Path) -> bool {
    let Some(parent) = path.parent() else {
        return false;
    };

    parent.components().any(|component| match component {
        Component::Normal(segment) => segment
            .to_str()
            .map(|name| {
                GENERATED_DIR_NAMES
                    .iter()
                    .any(|dir| name.eq_ignore_ascii_case(dir))
            })
            .unwrap_or(false),
        _ => false,
    })
}

/// Basename suffix match against known codegen output patterns
pub fn match_generated_name(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };
    let lower = name.to_ascii_lowercase();
    GENERATED_NAME_SUFFIXES.iter().any(|s| lower.ends_with(s))
}

/// Marker scan over the blob head (first ~512 bytes)
pub fn match_generated_header(header: &[u8]) -> bool {
    let lower = String::from_utf8_lossy(header).to_ascii_lowercase();

    if GENERATED_HEADER_MARKERS.iter().any(|m| lower.contains(m)) {
        return true;
    }

    lower.lines().any(is_generated_by_maker_line)
}

fn is_generated_by_maker_line(line: &str) -> bool {
    if EDIT_WARNING_MARKERS.iter().any(|m| line.contains(m)) && line.contains(GENERATION_STEM) {
        return true;
    }

    let trimmed = line.trim_start();
    let Some(rest) = COMMENT_PREFIXES
        .iter()
        .find_map(|prefix| trimmed.strip_prefix(prefix))
    else {
        return false;
    };
    let body = rest.trim_start();

    body.starts_with(GENERATOR_LEAD) || GENERATED_LINE_PHRASES.iter().any(|p| body.contains(p))
}

/// Phase A: Lock → Generated(path/name)
pub fn classify_by_name(path: &Path) -> Option<FileCategory> {
    if match_lock_file(path) {
        return Some(FileCategory::DependencyLock);
    }
    if match_generated_path(path) || match_generated_name(path) {
        return Some(FileCategory::Generated);
    }
    None
}

/// Phase B residue: Generated or None (→ SemanticText)
pub fn classify_by_header(header: &[u8]) -> Option<FileCategory> {
    if match_generated_header(header) {
        Some(FileCategory::Generated)
    } else {
        None
    }
}
