use std::path::Path;

const LOCK_FILES: &[&str] = &[
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lock",
    "deno.lock",
    "Cargo.lock",
    "go.sum",
    "Gopkg.lock",
    "glide.lock",
    "Gemfile.lock",
    "Pipfile.lock",
    "poetry.lock",
    "pdm.lock",
    "uv.lock",
    "conda-lock.yml",
    "conda-lock.yaml",
    "pixi.lock",
    "pylock.toml",
    "composer.lock",
    "pubspec.lock",
    "mix.lock",
    "rebar.lock",
    "packages.lock.json",
    "paket.lock",
    "Package.resolved",
    "Podfile.lock",
    "Cartfile.resolved",
    "conan.lock",
    "vcpkg-lock.json",
    ".terraform.lock.hcl",
    "flake.lock",
    "Manifest.toml",
    "renv.lock",
    "packrat.lock",
    "shard.lock",
    "stack.yaml.lock",
    "cabal.project.freeze",
    "cpanfile.snapshot",
    "dub.selections.json",
    "gradle.lockfile",
    "MODULE.bazel.lock",
    "Chart.lock",
    "helmfile.lock",
    "jsonnetfile.lock.json",
    "Brewfile.lock.json",
    "Berksfile.lock",
    "Policyfile.lock.json",
    "Puppetfile.lock",
    "spack.lock",
];

/// High-confidence path segments (directory components or full patterns).
const GENERATED_PATH_MARKERS: &[&str] = &[
    "/generated/",
    "/gen/",
    "/__generated__/",
    "/target/generated-sources/",
    "/build/generated/",
    "\\generated\\", // Windows-ish paths if ever present
];

/// File name patterns that strongly suggest codegen.
const GENERATED_NAME_SUFFIXES: &[&str] = &[
    ".pb.go",
    ".pb.ts",
    ".pb.rs",
    ".pb.swift",
    ".codegen.ts",
    ".codegen.js",
    ".g.dart",
    "_generated.go",
    "_generated.ts",
    "_generated.rs",
    ".generated.ts",
    ".generated.js",
];

/// Header markers (matched as case-insensitive substrings on raw bytes / UTF-8 lossy).
const GENERATED_HEADER_MARKERS: &[&str] = &[
    "@generated",
    "code generated by",
    "do not edit",
    "this file was automatically generated",
    "auto-generated",
    "autogenerated",
    "this file is generated",
];

pub fn is_dependency_lock(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };

    LOCK_FILES
        .iter()
        .any(|lock| name.eq_ignore_ascii_case(lock))
}

pub fn match_generated_path(path: &Path) -> bool {
    let s = path.to_string_lossy();
    let lower = s.to_ascii_lowercase();
    GENERATED_PATH_MARKERS
        .iter()
        .any(|m| lower.contains(&m.to_ascii_lowercase()))
}

pub fn match_generated_suffix(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
        return false;
    };
    let lower = name.to_ascii_lowercase();
    GENERATED_NAME_SUFFIXES
        .iter()
        .any(|suf| lower.ends_with(&suf.to_ascii_lowercase()))
}

pub fn match_generated_header(header: &[u8]) -> bool {
    let text = String::from_utf8_lossy(header).to_ascii_lowercase();
    GENERATED_HEADER_MARKERS.iter().any(|m| text.contains(m))
}
