name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: script/test.sh
        env:
          AUTOCOMMIT_E2E_API_KEY: ${{ secrets.AUTOCOMMIT_E2E_API_KEY }}
